id: IB50652C3
source: https://sakyaresearch.org
source_file: null
initial_creation_type: input
imported: '2022-06-19T09:26:05.270422'
last_modified: '2022-06-19T09:26:05.270433'
parser: null
source_metadata:
  title: Autobiography of lCe btsun mkhyen rab byams pa Ngag dbang lhun grub (1633–1703);
    Lamdre Lobshe, vol. ca, title no. 2
  author: ལྕེ་བཙུན་མཁྱེན་རབ་བྱམས་པ་ངག་དབང་ལྷུན་གྲུབ།
  description: 'Digital version 2.0 {Tibetan}; master xml (completed: 2013-09-04);
    unrevised, no thematic TEI markup'
  file_info:
  - 'Language: Tibetan'
  - 'Coverage: Full Text'
  - 'Accessible: publicly'
  responibilities:
  - Digital edition:ས་སྐྱ་ཞིབ་འཇུག་ཁང་། (src)
  - Text input:རྫོང་སར་ཁམས་བྱེའི་ལྔ་རིག་སློབ་གླིང་། སྡེ་དགེ་རྫོང་སར། (dzkj)
  - Editorial process:Mathias Fermer (mf), ཀུན་དགའ་རྡོ་རྗེ། (Kathmandu) (kun)
  - TEI Encoding:ས་སྐྱ་ཞིབ་འཇུག་ཁང་།
  - TEI Markup:-
  - Revisions/Corrections:-
  text_witnesses: https://sakyaresearch.org/sources/574
  bases:
    f752:
      title: Autobiography of lCe btsun mkhyen rab byams pa Ngag dbang lhun grub (1633–1703);
        Lamdre Lobshe, vol. ca, title no. 2
      order: 1
      base_file: f752.txt
statistics: {}
quality: {}
copyright:
  status: Unknown
  notice: ''
  info_url: null
license: null
